def counties():

    return [
        ("01", "Mombasa"),
        ("02", "Kwale"),
        ("03", "Kilifi"),
        ("04", "Tana River"),
        ("05", "Lamu"),
        ("06", "Taita-Taveta"),
        ("07", "Garissa"),
        ("08", "Wajir"),
        ("09", "Mandera"),
        ("10", "Marsabit"),
        ("11", "Isiolo"),
        ("12", "Meru"),
        ("13", "Tharaka-Nithi"),
        ("14", "Embu"),
        ("15", "Kitui"),
        ("16", "Machakos"),
        ("17", "Makueni"),
        ("18", "Nyandarua"),
        ("19", "Nyeri"),
        ("20", "Kirinyaga"),
        ("21", "Murang'a"),
        ("22", "Kiambu"),
        ("23", "Turkana"),
        ("24", "West Pokot"),
        ("25", "Samburu"),
        ("26", "Trans-Nzoia"),
        ("27", "Uasin-Gishu"),
        ("29", "Elgeyo-Marakwet"),
        ("30", "Nandi"),
        ("31", "Baringo"),
        ("32", "Laikipia"),
        ("33", "Nakuru"),
        ("34", "Narok"),
        ("35", "Kajiado"),
        ("36", "Kericho"),
        ("37", "Bomet"),
        ("38", "Kakamega"),
        ("39", "Bungoma"),
        ("40", "Busia"),
        ("41", "Siaya"),
        ("42", "Kisumu"),
        ("43", "Homa Bay"),
        ("44", "Migori"),
        ("45", "Kisii"),
        ("46", "Nyamira"),
        ("47", "Nairobi"),
    ]
