# Generated by Django 4.2 on 2023-05-02 09:00

import accounts.managers
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('date_created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('other_name', models.CharField(max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('primary_phone', models.CharField(blank=True, max_length=15)),
                ('secondary_phone', models.CharField(blank=True, max_length=15)),
                ('national_id', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('additional_email', models.EmailField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True, max_length=50)),
                ('additional_address', models.TextField(blank=True, max_length=50)),
                ('email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'accounts',
                'permissions': (('can_view_profile', 'Can view profiles'), ('can_change_profile', 'Can change profiles'), ('can_delete_profiles', 'Can delete profiles')),
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
